// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5eyrRKC6MzabAfkV2MkZQuTueRomzatg',
    appId: '1:1086490324015:web:29b50a36f9abfce0d62ada',
    messagingSenderId: '1086490324015',
    projectId: 'campus-locker',
    authDomain: 'campus-locker.firebaseapp.com',
    storageBucket: 'campus-locker.firebasestorage.app',
    measurementId: 'G-DRBFVRBRB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOS4i-OiSnu70zK6m7AZ6899VcABTTdaM',
    appId: '1:1086490324015:android:ffe6f2b11453e663d62ada',
    messagingSenderId: '1086490324015',
    projectId: 'campus-locker',
    storageBucket: 'campus-locker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3EiTL9H1ev5U-EIxM3f7gHVVISrZJjiQ',
    appId: '1:1086490324015:ios:03417e44613d815dd62ada',
    messagingSenderId: '1086490324015',
    projectId: 'campus-locker',
    storageBucket: 'campus-locker.firebasestorage.app',
    iosBundleId: 'com.example.lockerDisplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3EiTL9H1ev5U-EIxM3f7gHVVISrZJjiQ',
    appId: '1:1086490324015:ios:03417e44613d815dd62ada',
    messagingSenderId: '1086490324015',
    projectId: 'campus-locker',
    storageBucket: 'campus-locker.firebasestorage.app',
    iosBundleId: 'com.example.lockerDisplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5eyrRKC6MzabAfkV2MkZQuTueRomzatg',
    appId: '1:1086490324015:web:9a232513bda83329d62ada',
    messagingSenderId: '1086490324015',
    projectId: 'campus-locker',
    authDomain: 'campus-locker.firebaseapp.com',
    storageBucket: 'campus-locker.firebasestorage.app',
    measurementId: 'G-F2Q0X7EKL4',
  );
}
